#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

# Library configuration
bf-env "POSTGRESQL_LIB" "${BF_LIB}/postgresql"

POSTGRESQL_BACKUP="/backup"
bf-env "POSTGRESQL_DATA" "/data"
bf-env "POSTGRESQL_BACKUP" "${POSTGRESQL_BACKUP}"

bf-env "POSTGRESQL_BACKUP_FILENAME" "dump"
bf-env "POSTGRESQL_RESTORE" "${POSTGRESQL_BACKUP}/restore.sql"

bf-env "POSTGRESQL_SERVER_VERSION" `cat /usr/libexec/postgresql/PG_VERSION`

PG_VERSION="/data/PG_VERSION"
if [ -f "${PG_VERSION}" ]; then
    bf-env "POSTGRESQL_DATA_VERSION" `cat ${PG_VERSION}`
fi
