#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Check for application user and password.
#======================================================================================================================

[[ -z "${POSTGRESQL_USERNAME-}" || -z "${POSTGRESQL_PASSWORD-}" ]] \
    && bf-error "POSTGRESQL_USERNAME and POSTGRESQL_PASSWORD must be set."


#======================================================================================================================
# Add user with password.
#======================================================================================================================

# add user if it doesn't exist
if [ -z "$(getent passwd ${POSTGRESQL_USERNAME})" ] ; then

    bf-echo "Adding user ${POSTGRESQL_USERNAME}..."
    bf-adduser ${POSTGRESQL_USERNAME} 1001
    echo -e "${POSTGRESQL_PASSWORD}\n${POSTGRESQL_PASSWORD}" | passwd ${POSTGRESQL_USERNAME}
    bf-done

else

    bf-debug "User ${POSTGRESQL_USERNAME} exists."

fi
