#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Check for restore file.
#======================================================================================================================

if [ -f "${POSTGRESQL_RESTORE_PATH}" ] ; then

    # delete existing files
    bf-debug "Deleting existing files."
    bf-rmrf "${POSTGRESQL_DATA}/*"

    # run restore
    s6-setuidgid postgres ${POSTGRESQL_LIB}/init-restore

    # delete restore file
    rm "${POSTGRESQL_RESTORE_PATH}"

fi


#======================================================================================================================
# Run library init executable.
#======================================================================================================================

if [ ! -f ${POSTGRESQL_DATA}/PG_VERSION ] ; then

    # run init
    bf-debug "Initialise server."
    s6-setuidgid postgres ${POSTGRESQL_LIB}/init

else

    # be friendly..
    bf-debug "Server ready."

fi
