#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Run library config executable.
#======================================================================================================================

s6-setuidgid postgres ${POSTGRESQL_LIB}/config
