#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Check arguments.
#   1   Database name
#======================================================================================================================

[[ -z "${1-}" ]] && bf-error "You must provide the name of the database to export."
DATABASE=${1}


#======================================================================================================================
# Check database exists.
#======================================================================================================================

EXISTS=$(db-exists "${DATABASE}")
[[ "${EXISTS}" = "0" ]] && bf-error "Database '${DATABASE}' does not exist."


#======================================================================================================================
# Dump database to file.
#======================================================================================================================

EXPORT_FILE="${POSTGRESQL_BACKUP}/${DATABASE}.sql"
bf-echo "Exporting database '${DATABASE}' to ${EXPORT_FILE}..."
pg_dump "${DATABASE}" > "${EXPORT_FILE}" \
    || bf-error " .. unable to export database '${DATABASE}'."
bf-done
