#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Config is re-written every time in case environment variables have been changed.
#======================================================================================================================

bf-echo "Writing PostgreSQL config..."
bf-esh ${BF_TEMPLATES}/pg_hba.conf.esh \
    ${POSTGRESQL_DATA}/pg_hba.conf
bf-esh ${BF_TEMPLATES}/postgresql.conf.esh \
    ${POSTGRESQL_DATA}/postgresql.conf
bf-done
