#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Get import files (from backup directory).
#======================================================================================================================

bf-echo "Importing SQL files from ${POSTGRESQL_BACKUP}..."
for FILE in ${POSTGRESQL_BACKUP}/*.sql ; do

    # split out database name from file
    NAME=$(basename -- "${FILE}")
    DATABASE="${NAME%.*}"

    # create database if it does not exist
    EXISTS=$(db-exists "${DATABASE}")
    if [ "${EXISTS}" = "0" ] ; then
        bf-echo " .. creating '${DATABASE}'."
        createdb "${DATABASE}" --owner="${POSTGRESQL_USERNAME}"\
            || bf-notok "  . something went wrong."
    fi

    # execute dump file using psql
    bf-echo " .. importing '${DATABASE}'."
    psql "${DATABASE}" < ${FILE} \
        || bf-notok "  . something went wrong."

done
bf-done
