#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Get import files (from backup directory).
#======================================================================================================================

bf-echo "Importing SQL files from ${POSTGRESQL_BACKUP}..."
for FILE in ${POSTGRESQL_BACKUP}/*.sql ; do

    # split out database name from file
    NAME=$(basename -- "${FILE}")
    DATABASE="${NAME%.*}"

    # create database if it does not exist
    EXISTS=$(psql -l | grep "${DATABASE}" | wc -l)
    if [ "${EXISTS}" = "0" ] ; then
        bf-echo " .. creating '${DATABASE}'."
        createdb "${DATABASE}" -O "${POSTGRESQL_USERNAME}"\
            || bf-notok "  . something went wrong."
    fi

    # execute dump file using psql
    bf-echo " .. importing '${DATABASE}'."
    psql "${DATABASE}" < ${FILE} \
        || bf-notok "  . something went wrong."

done
bf-done
