#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Check for application user and password.
#======================================================================================================================

[[ -z "${POSTGRESQL_USERNAME-}" || -z "${POSTGRESQL_PASSWORD-}" ]] \
    && bf-error "POSTGRESQL_USERNAME and POSTGRESQL_PASSWORD must be set."


#======================================================================================================================
# Initialise server, create role and application database(s), enable remote connections.
#======================================================================================================================

# create specified role
bf-debug "Creating role ${POSTGRESQL_USERNAME}..."
echo -e "${POSTGRESQL_PASSWORD}\n${POSTGRESQL_PASSWORD}" | createuser --superuser --pwprompt ${POSTGRESQL_USERNAME}

# create database(s)
bf-debug "Creating..."
if [ ! -z "${POSTGRESQL_DATABASE-}" ] ; then

    bf-debug " .. specified database(s):"
    DATABASES=$(echo ${POSTGRESQL_DATABASE} | tr "," "\n")

    for DATABASE in ${DATABASES} ; do
        bf-debug " .. ${DATABASE}."
        createdb "${DATABASE}" --owner="${POSTGRESQL_USERNAME}"
    done

# no database specified so use username as database name
else

    bf-debug " .. application database: ${POSTGRESQL_USERNAME}."
    createdb "${POSTGRESQL_USERNAME}" --owner="${POSTGRESQL_USERNAME}"

fi
