#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Initialise server, restore from dump file.
#======================================================================================================================

# initialise server
bf-debug "Running db-init..."
initdb -D "${POSTGRESQL_DATA}"

# start server for restore
bf-echo "Starting PostgreSQL for restore."
pg_ctl start -D "${POSTGRESQL_DATA}"

# run restore
psql -f "${POSTGRESQL_RESTORE}"

# stop server
pg_ctl stop -D "${POSTGRESQL_DATA}"
