name: publish-14

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-14:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read PostgreSQL version - minor
        uses: bfren/read-file@v1
        with:
          file: ./14/POSTGRESQL_MINOR
        id: postgresql_minor
      -
        name: Read PostgreSQL version - build
        uses: bfren/read-file@v1
        with:
          file: ./14/POSTGRESQL_BUILD
        id: postgresql_build
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION_MAJOR
        id: version_major
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./14/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/postgresql:postgresql14
            bfren/postgresql:postgresql14-${{ steps.version_major.outputs.contents }}
            bfren/postgresql:postgresql14-${{ steps.version_minor.outputs.contents }}
            bfren/postgresql:postgresql14-${{ steps.version.outputs.contents }}
            bfren/postgresql:postgresql${{ steps.postgresql_minor.outputs.contents }}
            bfren/postgresql:postgresql${{ steps.postgresql_minor.outputs.contents }}-${{ steps.version.outputs.contents }}
            bfren/postgresql:postgresql${{ steps.postgresql_build.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
