#!/command/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Show helpful log message.
#======================================================================================================================

s6-setuidgid postgres ${POSTGRESQL_LIB}/finish
bf-svc-finish -t
